{
  "tracks": {
   "href": "https://api.spotify.com/v1/search?query=Ace+of+Base+The+Sign&type=track&offset=0&limit=1",
   "items": [
    {
     "album": {
      "album_type": "album",
      "artists": [
       {
        "external_urls": {
         "spotify": "https://open.spotify.com/artist/5ksRONqssB7BR161NTtJAm"
        },
        "href": "https://api.spotify.com/v1/artists/5ksRONqssB7BR161NTtJAm",
        "id": "5ksRONqssB7BR161NTtJAm",
        "name": "Ace of Base",
        "type": "artist",
        "uri": "spotify:artist:5ksRONqssB7BR161NTtJAm"
       }
      ],
      "available_markets": [
       "AD",
       "AR",
       "AT",
       "AU",
       "BE",
       "BG",
       "BO",
       "BR",
       "CA",
       "CH",
       "CL",
       "CO",
       "CR",
       "CY",
       "CZ",
       "DE",
       "DK",
       "DO",
       "EC",
       "EE",
       "ES",
       "FI",
       "FR",
       "GB",
       "GR",
       "GT",
       "HK",
       "HN",
       "HU",
       "ID",
       "IE",
       "IL",
       "IS",
       "IT",
       "JP",
       "LI",
       "LT",
       "LU",
       "LV",
       "MC",
       "MT",
       "MX",
       "MY",
       "NI",
       "NL",
       "NO",
       "NZ",
       "PA",
       "PE",
       "PH",
       "PL",
       "PT",
       "PY",
       "RO",
       "SE",
       "SG",
       "SK",
       "SV",
       "TH",
       "TR",
       "TW",
       "US",
       "UY",
       "VN",
       "ZA"
      ],
      "external_urls": {
       "spotify": "https://open.spotify.com/album/5UwIyIyFzkM7wKeGtRJPgB"
      },
      "href": "https://api.spotify.com/v1/albums/5UwIyIyFzkM7wKeGtRJPgB",
      "id": "5UwIyIyFzkM7wKeGtRJPgB",
      "images": [
       {
        "height": 600,
        "url": "https://i.scdn.co/image/420f7961d01701f6d4fe8fcd6c99fde0d13e7da7",
        "width": 600
       },
       {
        "height": 300,
        "url": "https://i.scdn.co/image/14a8250ab9767f68eb58a7bcc1b2864dada763bf",
        "width": 300
       },
       {
        "height": 64,
        "url": "https://i.scdn.co/image/81d371b69683de3224b978eff7d57d2e9ddc9994",
        "width": 64
       }
      ],
      "name": "The Sign (US Album) [Remastered]",
      "release_date": "1993",
      "release_date_precision": "year",
      "type": "album",
      "uri": "spotify:album:5UwIyIyFzkM7wKeGtRJPgB"
     },
     "artists": [
      {
       "external_urls": {
        "spotify": "https://open.spotify.com/artist/5ksRONqssB7BR161NTtJAm"
       },
       "href": "https://api.spotify.com/v1/artists/5ksRONqssB7BR161NTtJAm",
       "id": "5ksRONqssB7BR161NTtJAm",
       "name": "Ace of Base",
       "type": "artist",
       "uri": "spotify:artist:5ksRONqssB7BR161NTtJAm"
      }
     ],
     "available_markets": [
      "AD",
      "AR",
      "AT",
      "AU",
      "BE",
      "BG",
      "BO",
      "BR",
      "CA",
      "CH",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DE",
      "DK",
      "DO",
      "EC",
      "EE",
      "ES",
      "FI",
      "FR",
      "GB",
      "GR",
      "GT",
      "HK",
      "HN",
      "HU",
      "ID",
      "IE",
      "IL",
      "IS",
      "IT",
      "JP",
      "LI",
      "LT",
      "LU",
      "LV",
      "MC",
      "MT",
      "MX",
      "MY",
      "NI",
      "NL",
      "NO",
      "NZ",
      "PA",
      "PE",
      "PH",
      "PL",
      "PT",
      "PY",
      "RO",
      "SE",
      "SG",
      "SK",
      "SV",
      "TH",
      "TR",
      "TW",
      "US",
      "UY",
      "VN",
      "ZA"
     ],
     "disc_number": 1,
     "duration_ms": 191240,
     "explicit": false,
     "external_ids": {
      "isrc": "SEVJH0803404"
     },
     "external_urls": {
      "spotify": "https://open.spotify.com/track/0hrBpAOgrt8RXigk83LLNE"
     },
     "href": "https://api.spotify.com/v1/tracks/0hrBpAOgrt8RXigk83LLNE",
     "id": "0hrBpAOgrt8RXigk83LLNE",
     "name": "The Sign",
     "popularity": 70,
     "preview_url": "https://p.scdn.co/mp3-preview/4c463359f67dd3546db7294d236dd0ae991882ff?cid=33d600d1b3204e2780287cd08a53d621",
     "track_number": 4,
     "type": "track",
     "uri": "spotify:track:0hrBpAOgrt8RXigk83LLNE"
    }
   ],
   "limit": 1,
   "next": "https://api.spotify.com/v1/search?query=Ace+of+Base+The+Sign&type=track&offset=1&limit=1",
   "offset": 0,
   "previous": null,
   "total": 115
  }
 }